#!/bin/sh

files="$(git diff --name-only ./src | grep -E '\.(ts|js)$')"

pad_right() {
  echo -en "\e[2m"
  printf "%-*s" "$2" "$1"
  echo -en "\e[0m"
}

echo -n "$(pad_right "Linting Commit..." 45)"

lint_result="$(eval "bun run lint_hook $files 2> /dev/null")"
if [ $? -ne 0 ]; then
  echo -e "\033[31mFAIL\033[39m"
  echo -e "$lint_result"

  exit 1
fi

echo -e "\033[32mPASSED\033[39m"

# echo -n "$(pad_right "Scanning Commit For Vulns..." 45)"

# lint_result=$"$(eval "bun snyk code test 2> /dev/null")"
# if [ $? -ne 0 ]; then
#   echo -e "\033[31mFAIL\033[39m"
#   echo -e "$lint_result"

#   exit 1
# fi

# echo -e "\033[32mPASSED\033[39m"

echo -n "$(pad_right "Prettifying Commit..." 45)"
bun prettier . --write &>/dev/null
if [ $? -ne 0 ]; then
  echo -e "\033[31mFAIL\033[39m"
  exit 1
fi

echo -e "\033[32mPASSED\033[39m"
